services:
  mcp-server-snowflake:
    build:
      context: .
      dockerfile: docker/server/Dockerfile
      platforms:
        - linux/amd64
    image: ${SNOWFLAKE_ACCOUNT}.registry.snowflakecomputing.com/cube_testing/public/awesome_images/mcp-server:latest
    container_name: mcp-server-snowflake
    environment:
      - SNOWFLAKE_PAT=${SNOWFLAKE_PAT}
      - SNOWFLAKE_ACCOUNT=${SNOWFLAKE_ACCOUNT}
      - SNOWFLAKE_USER=${SNOWFLAKE_USER}
    volumes:
      - ${HOME}/.mcp/snowflake_mcp_config.yaml:/app/services/custom_config.yaml:ro
    ports:
      - "9000:9000"
    restart: unless-stopped
  marimo-notebook:
    build:
      context: .
      dockerfile: docker/notebook/Dockerfile
      platforms:
        - linux/amd64
    image: ${SNOWFLAKE_ACCOUNT}.registry.snowflakecomputing.com/cube_testing/public/awesome_images/marimo-notebook:latest
    container_name: marimo-notebook
    ports:
      - "2718:2718"
    restart: unless-stopped
